Support adding roles for PowerMax
dell/karavi-authorization pull request #84
Opened 2021-04-29 21:14 UTC by atye

# Description

This PR adds support for creating a role for a PowerMax system.

To validate a PowerMax role, we verify that the system ID exists as an authorized storage system and verify that the specified Storage Resrouce Pool exists on the PowerMax.

# Issues

List the issues impacted by this PR:

| Issue ID |
| -------- |
|     #83      |

# Checklist:

- [x] I have performed a self-review of my own changes.

2021-04-29 21:17 UTC, ioeicicdsvc commented
@atye: Thank you for submitting your pull request!

Please make sure you have followed our contributing guidelines. We will review it as soon as possible.

------------------------------------------------------------------------------------------------------------------------
We want your feedback! If you have any questions or suggestions regarding our contributing process/workflow, please reach out to us at karavi@dell.com.

2021-04-30 12:31 UTC, hoppea2 submitted a review, later dismissed

2021-04-30 13:36 UTC, sharmilarama requested changes
LGTM. Please look in to failed tests.

2021-04-30 17:04 UTC, medegw01 approved these changes

2021-05-03 13:09 UTC, hoppea2 approved these changes

2021-05-03 19:13 UTC, atye commented
> LGTM. Please look in to failed tests.

Tests have been fixed via refactoring of the cobra commands with constructors rather than global variables.

2021-05-03 23:30 UTC, ianbibby approved these changes
👍

2021-05-03 23:33 UTC, ianbibby requested changes
Changes look good.  There are some failing checks that just need to be addressed, e.g. gosec.

2021-05-03 23:50 UTC, atye commented
> Changes look good. There are some failing checks that just need to be addressed, e.g. gosec.

Fixed the gosec issue. There is also a security issue in jwt-go which is fixed in https://github.com/dgrijalva/jwt-go/releases/tag/v4.0.0-preview1. I'll update the package.

2021-05-04 13:44 UTC, sharmilarama commented on cmd/karavictl/cmd/rolebinding_delete_test.go
> +		//deleteRoleBindingCmd := NewDeleteRoleBindingCmd()
remove comment

2021-05-04 17:01 UTC, atye commented on cmd/karavictl/cmd/rolebinding_delete_test.go
> +		//deleteRoleBindingCmd := NewDeleteRoleBindingCmd()
Fixed.

2021-05-04 17:15 UTC, medegw01 approved these changes

2021-05-04 17:17 UTC, ianbibby approved these changes

2021-05-04 17:26 UTC, sharmilarama approved these changes
LGTM

2021-05-04 17:26 UTC, merged